version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd ./be
      - npm install -g typescript  
      - npm install 

  build:
    commands:
      - echo "Building the TypeScript application..."
      - npm run build
      - echo "Build complete."

artifacts:
  files:
    - '**/*'  
  base-directory: './be' 

